name: Unzip and Commit Contents

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - '*.zip' # Trigger when zip files are added or modified

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Find and unzip files
        run: |
          # Find all zip files in the repository
          zip_files=$(find . -name "*.zip" -type f | grep -v ".git")
          
          if [ -z "$zip_files" ]; then
            echo "No zip files found in the repository"
            exit 0
          fi
          
          echo "Found zip files:"
          echo "$zip_files"
          
          # Process each zip file
          for zip_file in $zip_files; do
            echo "Processing: $zip_file"
            
            # Get the base name without extension for extraction directory
            base_name=$(basename "$zip_file" .zip)
            
            # Check if zip file contains a root directory
            root_dir=$(unzip -l "$zip_file" | awk 'NR>3 {print $4}' | head -1 | cut -d'/' -f1)
            
            # Extract the zip file
            unzip -o "$zip_file"
            
            # If the extracted content is in a subdirectory, move it to root
            if [ -d "$root_dir" ] && [ "$root_dir" != "." ]; then
              echo "Moving contents from $root_dir to repository root"
              
              # Copy contents from subdirectory to root, excluding the zip file itself
              cp -r "$root_dir"/* .
              cp -r "$root_dir"/.[^.]* . 2>/dev/null || true
              
              # Remove the extracted directory
              rm -rf "$root_dir"
            fi
            
            echo "Successfully extracted: $zip_file"
          done

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          # Add all new files
          git add .
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit the changes
          git commit -m "Auto-extract: Unzip and commit archive contents

          This commit was automatically generated by GitHub Actions.
          Contents from zip files have been extracted and committed to the repository."
          
          # Push the changes
          git push origin main

      - name: Summary
        run: |
          echo "✅ Successfully processed zip files and committed contents to main branch"
          echo "📁 Extracted files are now available in the repository"