name: Unzip and Commit Contents

on:
  workflow_dispatch: # Run thủ công
  push:
    branches:
      - main
    paths:
      - '*.zip' # Trigger khi có file zip mới

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Find and unzip files
        run: |
          zip_files=$(find . -name "*.zip" -type f | grep -v ".git")
          
          if [ -z "$zip_files" ]; then
            echo "⚠️ No zip files found"
            exit 0
          fi
          
          echo "📦 Found zip files:"
          echo "$zip_files"
          
          for zip_file in $zip_files; do
            echo "🔓 Processing: $zip_file"
            unzip -o "$zip_file" -d ./unzipped

            # Move contents ra root
            cp -r ./unzipped/* .
            cp -r ./unzipped/.[^.]* . 2>/dev/null || true
            rm -rf ./unzipped

            # Nếu muốn xoá file zip sau khi giải nén, bật dòng này:
            # rm -f "$zip_file"

            echo "✅ Extracted: $zip_file"
          done

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add .

          if git diff --staged --quiet; then
            echo "ℹ️ No changes to commit"
            exit 0
          fi

          git commit -m "Auto-extract: unzip and commit archive contents"
          git push origin main

      - name: Summary
        run: echo "🎉 Zip files extracted and committed to main branch!"
